# -*- coding: utf-8 -*-
"""Fractals.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zxItpG24A86ggpF9UqVkoRy4K6U2nlva
"""

country_colors = {
    'India' : ["FF9933","FFFFFF","128807","000088"], 'UAE' : ["FF0000","00732F","FFFFFF","000000"], 'USA' : ["3C3B6E","FFFFFF","B22234","000000"]
}

from PIL import Image

def RGB_val(Hexcode):
	R_value = '0x' + Hexcode[0:2]
	G_value = '0x' + Hexcode[2:4]
	B_value = '0x' + Hexcode[4:6]
	# print()
	# print(R_value, G_value, B_value)
	
	return (int(R_value,0), int(G_value,0), int(B_value,0))

if __name__ == "__main__":
	w, h = 857,1142
	country = 'UAE'
	bitmap = Image.new("RGB", (w,h), "white")
	pix = bitmap.load()
	cX =  -0.54
	cY = 0.54
	MaxIter = 255
	for x in range(w):
		for y in range(h):
			zx = 1.5*(x-w/2)/(0.5*w)
			zy = 1.0*(y-h/2)/(0.5*h)
			i = MaxIter
			while zx*zx + zy*zy < 4 and i > 1:
				tmp = zx*zx - zy*zy + cX
				zy,zx = 2.0*zx*zy + cY, tmp
				i -= 1
			pix[x,y] = (i<<10)#+(i<<25)+i*5  (generating colours)
bitmap

bitmap.save('fract.png')

#for using country flag colours
if i<64:
				pix[x,y] =  (RGB_val(country_colors[country][0]))
			elif i>64 and i<128:
				pix[x,y] =  (RGB_val(country_colors[country][1]))
			elif i>128 and i<230:
				pix[x,y] =  (RGB_val(country_colors[country][2]))
			elif i>230 and i<256:
				pix[x,y] =  (RGB_val(country_colors[country][0]))
			else:
				pix[x,y] =  (RGB_val(country_colors[country][0]))


#USA
      if i<64:
				pix[x,y] =  (RGB_val(country_colors[country][0]))
			elif i>64 and i<128:
				pix[x,y] =  (RGB_val(country_colors[country][1]))
			elif i>128 and i<192:
				pix[x,y] =  (RGB_val(country_colors[country][2]))
			elif i>192 and i<256:
				pix[x,y] =  (255,255,255)
			else:
				pix[x,y] =  (RGB_val(country_colors[country][3]))
			if i<85:
				pix[x,y] =  (RGB_val(country_colors[country][0]))
			elif i>85 and i<170:
				pix[x,y] =  (RGB_val(country_colors[country][2]))
			elif i>170 and i<256:
				pix[x,y] =  (RGB_val(country_colors[country][1]))
			else:
				pix[x,y] =  (RGB_val(country_colors[country][2]))
